import { Product, SectionType } from '@/types/product';

export const products: Product[] = [
  // Men's Jackets (4)
  {
    id: '1',
    slug: 'heritage-biker-jacket',
    name: 'Heritage Biker Jacket',
    category: 'Men · Jackets',
    gender: 'men',
    type: 'jacket',
    price: 289,
    originalPrice: 380,
    origin: 'Full-grain cowhide · Sialkot',
    leather: 'Full-grain',
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '🧥',
    badge: 'Sale',
    rating: 4.9,
    reviewCount: 128,
    averageRating: 4.9,
    sections: ['featured', 'selling', 'rated'],
    rank: 2,
    ratingNum: 4.9,
    colors: ['#7C3A2D', '#1C1810', '#5A3020'],
    inStock: true,
    stockCount: 7,
    description: 'The Heritage Biker Jacket is handcrafted from full-grain cowhide leather at our Sialkot atelier. This timeless piece features hand-stitched construction with waxed linen thread, solid brass hardware, and a quilted satin lining for premium comfort and durability.',
    shortDescription: 'Full-Grain Cowhide — Hand-Stitched in Sialkot',
    colorOptions: [
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
      { name: 'Midnight Black', hex: '#1C1810', code: 'MB' },
      { name: 'Dark Espresso', hex: '#2A1810', code: 'DE' },
      { name: 'Chestnut', hex: '#5A3020', code: 'CH' },
      { name: 'Vintage Tan', hex: '#8A6040', code: 'VT' },
    ],
    sizeOptions: [
      { size: 'XS', label: 'XS', measurements: 'Chest 34–36" · Waist 28–30" · Length 24"', inStock: true },
      { size: 'S', label: 'S', measurements: 'Chest 36–38" · Waist 30–32" · Length 25"', inStock: true },
      { size: 'M', label: 'M', measurements: 'Chest 38–40" · Waist 32–34" · Length 26"', inStock: true },
      { size: 'L', label: 'L', measurements: 'Chest 40–42" · Waist 34–36" · Length 27"', inStock: true },
      { size: 'XL', label: 'XL', measurements: 'Chest 42–44" · Waist 36–38" · Length 28"', inStock: true },
      { size: 'XXL', label: 'XXL', measurements: 'Chest 44–46" · Waist 38–40" · Length 29"', inStock: false },
    ],
    productImages: [
      { emoji: '🧥', label: 'Full-Grain Cowhide · Cognac Brown', description: 'Front view of Heritage Biker Jacket' },
      { emoji: '🔍', label: 'Hardware Detail · Brass Zipper', description: 'Solid brass YKK zipper detail' },
      { emoji: '📐', label: 'Silhouette · Slim Fit Profile', description: 'Slim fit profile for modern styling' },
      { emoji: '🧵', label: 'Stitching Detail · Waxed Linen Thread', description: 'Double-stitched seams with waxed linen' },
      { emoji: '🏷', label: 'Interior Label · Sialkot Atelier', description: 'Hand-branded interior label' },
      { emoji: '✨', label: 'Patina Preview · 6 Months of Wear', description: 'Beautiful patina development over time' },
    ],
    features: [
      { icon: '🐄', title: 'Full-Grain Cowhide', description: 'Top layer of the hide — strongest, most character-rich leather money can buy' },
      { icon: '🧵', title: 'Hand-Stitched', description: 'Waxed linen thread sewn by master craftsmen with 20+ years experience' },
      { icon: '🔩', title: 'Brass Hardware', description: 'Solid antique-finish brass throughout — no plating, no shortcuts' },
      { icon: '✨', title: 'Ages Beautifully', description: 'Develops a unique patina over time, becoming more characterful with every wear' },
    ],
    accordions: [
      {
        title: 'Product Details',
        content: [
          'Full-grain cowhide leather — top layer of the hide, the strongest and most beautiful',
          'Hand-stitched with waxed linen thread by master craftsmen in Sialkot',
          'YKK brass hardware — zippers and D-rings that will outlast the jacket',
          'Quilted satin lining for warmth and premium feel',
          '4 exterior pockets, 2 interior pockets with snap closure',
          'Adjustable waist belt with antique-brass buckle',
          'Ages beautifully — develops a unique patina that makes it yours',
        ],
      },
      {
        title: 'Materials & Craftsmanship',
        content: {
          'Outer Material': '100% Full-Grain Cowhide (1.2mm thickness)',
          'Lining': '100% Satin — quilted at chest, smooth at sleeves',
          'Hardware': 'Solid brass, antique finish, YKK zippers',
          'Stitching': 'Waxed linen thread, double-stitched seams',
          'Origin': 'Handcrafted in Sialkot, Pakistan',
          'Tanning': 'Vegetable-tanned, chrome-free',
        },
      },
      {
        title: 'Sizing & Fit',
        content: {
          'XS': 'Chest 34–36" · Waist 28–30" · Length 24"',
          'S': 'Chest 36–38" · Waist 30–32" · Length 25"',
          'M': 'Chest 38–40" · Waist 32–34" · Length 26"',
          'L': 'Chest 40–42" · Waist 34–36" · Length 27"',
          'XL': 'Chest 42–44" · Waist 36–38" · Length 28"',
        },
      },
      {
        title: 'Care Instructions',
        content: [
          'Wipe clean with a dry or barely damp cloth — never soak or machine wash',
          'Condition with quality leather balm every 6–12 months',
          'Store on a wide shoulder hanger to maintain shape',
          'Keep away from direct heat sources and prolonged sunlight',
          'If wet, let dry naturally away from heat; reshape while damp',
        ],
      },
      {
        title: 'Shipping & Returns',
        content: [
          'Free shipping to Europe on orders above €150',
          'Standard delivery: 7–12 business days from Sialkot',
          'DHL Express available at checkout (3–5 days)',
          '30-day returns on unworn items in original condition',
          'Free return shipping within the EU',
        ],
      },
    ],
    trustBadges: ['🚚 Free EU Shipping', '↩️ 30-Day Returns', '🔒 Secure Payment'],
    craftStory: {
      title: 'Crafted to Last a Lifetime',
      description: 'Every jacket begins as a single hide selected by our master craftsmen in Sialkot — the leather capital of the world. We use only the top 12% of each hide, ensuring every piece you receive is flawless, supple, and ready to age into something deeply personal.',
      stats: [
        { label: 'Years of Craft', value: '600+' },
        { label: 'Master Artisans', value: '42' },
        { label: 'Ethical Made', value: '100%' },
      ],
    },
    reviews: [
      {
        id: '1',
        author: 'Marcus H.',
        location: 'Berlin, Germany',
        date: 'March 2025',
        rating: 5,
        text: 'I\'ve owned many leather jackets, but this is the first one that felt like an heirloom from the day I put it on. The leather is extraordinary — thick, supple, and the cognac colour is even more beautiful in person.',
        verified: true,
      },
      {
        id: '2',
        author: 'Thomas V.',
        location: 'Amsterdam, NL',
        date: 'February 2025',
        rating: 5,
        text: 'Ordered size M as suggested. Fits perfectly — slim but not restrictive. The hardware is solid brass, not that cheap zinc you find elsewhere. Delivery took 9 days to Amsterdam. Absolutely worth the wait.',
        verified: true,
      },
      {
        id: '3',
        author: 'Luca B.',
        location: 'Milan, Italy',
        date: 'January 2025',
        rating: 5,
        text: 'The craftsmanship is simply unmatched at this price point. I had it custom-fitted by a tailor and the leather was so clean and even, he said he\'d never worked with anything of this quality outside of bespoke Florentine pieces.',
        verified: true,
      },
    ],
    relatedProducts: ['2', '12', '13', '9'],
  },
  {
    id: '2',
    slug: 'classic-leather-blazer',
    name: 'Classic Leather Blazer',
    category: 'Men · Jackets',
    gender: 'men',
    type: 'jacket',
    price: 325,
    origin: 'Premium calf leather · Sialkot',
    leather: 'Calf',
    imageUrl: 'https://images.unsplash.com/photo-1539533057440-7cf90262271e?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '🧥',
    badge: 'New',
    rating: 4.8,
    reviewCount: 94,
    averageRating: 4.8,
    sections: ['featured', 'new'],
    colors: ['#7C3A2D', '#C9A96E', '#2A1810'],
    inStock: true,
    stockCount: 5,
    colorOptions: [
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
      { name: 'Brass Gold', hex: '#C9A96E', code: 'BG' },
      { name: 'Night Black', hex: '#2A1810', code: 'NB' },
    ],
    sizeOptions: [
      { size: 'XS', label: 'XS', inStock: true },
      { size: 'S', label: 'S', inStock: true },
      { size: 'M', label: 'M', inStock: true },
      { size: 'L', label: 'L', inStock: true },
      { size: 'XL', label: 'XL', inStock: true },
    ],
    relatedProducts: ['1', '3', '12', '9'],
  },
  {
    id: '3',
    slug: 'aviator-leather-jacket',
    name: 'Aviator Leather Jacket',
    category: 'Men · Jackets',
    gender: 'men',
    type: 'jacket',
    price: 299,
    origin: 'Vegetable-tanned · Sialkot',
    leather: 'Vegetable-tanned',
    imageUrl: 'https://images.unsplash.com/photo-1590736969955-71cc94901144?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '🧥',
    rating: 4.7,
    reviewCount: 112,
    averageRating: 4.7,
    sections: ['featured'],
    colors: ['#1C1810', '#5A3020'],
    inStock: true,
    stockCount: 3,
    colorOptions: [
      { name: 'Midnight Black', hex: '#1C1810', code: 'MB' },
      { name: 'Chestnut', hex: '#5A3020', code: 'CH' },
    ],
    sizeOptions: [
      { size: 'XS', label: 'XS', inStock: false },
      { size: 'S', label: 'S', inStock: true },
      { size: 'M', label: 'M', inStock: true },
      { size: 'L', label: 'L', inStock: true },
      { size: 'XL', label: 'XL', inStock: false },
    ],
    relatedProducts: ['1', '2', '13', '9'],
  },
  {
    id: '4',
    slug: 'minimal-leather-jacket',
    name: 'Minimal Leather Jacket',
    category: 'Men · Jackets',
    gender: 'men',
    type: 'jacket',
    price: 275,
    originalPrice: 350,
    origin: 'Nappa leather · Sialkot',
    leather: 'Nappa',
    imageUrl: 'https://images.unsplash.com/photo-1597982212624-e27f42e73144?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '🧥',
    badge: 'Sale',
    rating: 4.6,
    reviewCount: 87,
    averageRating: 4.6,
    sections: ['featured'],
    colors: ['#1C1810', '#2A1810'],
    inStock: true,
    stockCount: 12,
    colorOptions: [
      { name: 'Midnight Black', hex: '#1C1810', code: 'MB' },
      { name: 'Charcoal', hex: '#2A1810', code: 'CH' },
    ],
    sizeOptions: [
      { size: 'XS', label: 'XS', inStock: true },
      { size: 'S', label: 'S', inStock: true },
      { size: 'M', label: 'M', inStock: true },
      { size: 'L', label: 'L', inStock: true },
      { size: 'XL', label: 'XL', inStock: true },
    ],
    relatedProducts: ['1', '2', '3', '9'],
  },
  // Men's Shoes (4)
  {
    id: '5',
    slug: 'oxford-derby-shoe',
    name: 'Oxford Derby Shoe',
    category: 'Men · Shoes',
    gender: 'men',
    type: 'shoe',
    price: 195,
    origin: 'Calfskin leather · Sialkot',
    leather: 'Calfskin',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👞',
    rating: 4.7,
    reviewCount: 56,
    averageRating: 4.7,
    sections: ['featured'],
    colors: ['#7C3A2D', '#1C1810'],
    inStock: true,
    stockCount: 8,
    colorOptions: [
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
      { name: 'Midnight Black', hex: '#1C1810', code: 'MB' },
    ],
    sizeOptions: [
      { size: '6', label: '6', inStock: true },
      { size: '6.5', label: '6.5', inStock: true },
      { size: '7', label: '7', inStock: true },
      { size: '7.5', label: '7.5', inStock: true },
      { size: '8', label: '8', inStock: true },
      { size: '9', label: '9', inStock: true },
      { size: '10', label: '10', inStock: true },
      { size: '11', label: '11', inStock: true },
      { size: '12', label: '12', inStock: true },
    ],
    relatedProducts: ['6', '7', '8', '12'],
  },
  {
    id: '6',
    slug: 'italian-loafer',
    name: 'Italian Loafer',
    category: 'Men · Shoes',
    gender: 'men',
    type: 'shoe',
    price: 185,
    origin: 'Premium leather · Sialkot',
    leather: 'Premium',
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👞',
    badge: 'Hot',
    rating: 4.8,
    reviewCount: 142,
    averageRating: 4.8,
    sections: ['featured', 'selling'],
    rank: 6,
    colors: ['#7C3A2D', '#1C1810'],
    inStock: true,
    stockCount: 15,
    colorOptions: [
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
      { name: 'Midnight Black', hex: '#1C1810', code: 'MB' },
    ],
    sizeOptions: [
      { size: '6', label: '6', inStock: true },
      { size: '7', label: '7', inStock: true },
      { size: '8', label: '8', inStock: true },
      { size: '9', label: '9', inStock: true },
      { size: '10', label: '10', inStock: true },
      { size: '11', label: '11', inStock: true },
      { size: '12', label: '12', inStock: true },
    ],
    relatedProducts: ['5', '7', '8', '13'],
  },
  {
    id: '7',
    slug: 'chelsea-boot',
    name: 'Chelsea Boot',
    category: 'Men · Shoes',
    gender: 'men',
    type: 'shoe',
    price: 225,
    origin: 'Full-grain leather · Sialkot',
    leather: 'Full-grain',
    imageUrl: 'https://images.unsplash.com/photo-1543163521-9efcc06b9005?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👞',
    rating: 4.9,
    reviewCount: 128,
    averageRating: 4.9,
    sections: ['featured', 'rated'],
    ratingNum: 4.8,
    colors: ['#7C3A2D', '#1C1810'],
    inStock: true,
    stockCount: 6,
    colorOptions: [
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
      { name: 'Midnight Black', hex: '#1C1810', code: 'MB' },
    ],
    sizeOptions: [
      { size: '6', label: '6', inStock: true },
      { size: '7', label: '7', inStock: true },
      { size: '8', label: '8', inStock: true },
      { size: '9', label: '9', inStock: true },
      { size: '10', label: '10', inStock: false },
      { size: '11', label: '11', inStock: true },
      { size: '12', label: '12', inStock: true },
    ],
    relatedProducts: ['5', '6', '8', '12'],
  },
  {
    id: '8',
    slug: 'casual-leather-sneaker',
    name: 'Casual Leather Sneaker',
    category: 'Men · Shoes',
    gender: 'men',
    type: 'shoe',
    price: 165,
    originalPrice: 210,
    origin: 'Soft leather · Sialkot',
    leather: 'Soft',
    imageUrl: 'https://images.unsplash.com/photo-1549928736-42cabea2b519?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👞',
    badge: 'Sale',
    rating: 4.5,
    reviewCount: 73,
    averageRating: 4.5,
    sections: ['featured'],
    colors: ['#1C1810', '#5A3020'],
    inStock: true,
    stockCount: 20,
    colorOptions: [
      { name: 'Midnight Black', hex: '#1C1810', code: 'MB' },
      { name: 'Chestnut', hex: '#5A3020', code: 'CH' },
    ],
    sizeOptions: [
      { size: '6', label: '6', inStock: true },
      { size: '7', label: '7', inStock: true },
      { size: '8', label: '8', inStock: true },
      { size: '9', label: '9', inStock: true },
      { size: '10', label: '10', inStock: true },
      { size: '11', label: '11', inStock: true },
      { size: '12', label: '12', inStock: true },
    ],
    relatedProducts: ['5', '6', '7', '9'],
  },
  // Men's Wallets (3)
  {
    id: '9',
    slug: 'slim-bifold-wallet',
    name: 'Slim Bifold Wallet',
    category: 'Men · Wallets',
    gender: 'men',
    type: 'wallet',
    price: 65,
    origin: 'Vegetable-tanned · Sialkot',
    leather: 'Vegetable-tanned',
    imageUrl: 'https://images.unsplash.com/photo-1627123834957-fc67c41db6dc?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👛',
    rating: 4.8,
    reviewCount: 85,
    averageRating: 4.8,
    sections: ['featured'],
    colors: ['#1C1810', '#5A3020'],
    inStock: true,
    stockCount: 25,
    colorOptions: [
      { name: 'Midnight Black', hex: '#1C1810', code: 'MB' },
      { name: 'Chestnut', hex: '#5A3020', code: 'CH' },
    ],
    sizeOptions: [
      { size: 'One Size', label: 'One Size', inStock: true },
    ],
    relatedProducts: ['10', '11', '12', '1'],
  },
  {
    id: '10',
    slug: 'premium-trifold-wallet',
    name: 'Premium Trifold Wallet',
    category: 'Men · Wallets',
    gender: 'men',
    type: 'wallet',
    price: 85,
    origin: 'Full-grain leather · Sialkot',
    leather: 'Full-grain',
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👛',
    badge: 'New',
    rating: 4.9,
    reviewCount: 67,
    averageRating: 4.9,
    sections: ['featured', 'new'],
    colors: ['#1C1810', '#7C3A2D'],
    inStock: true,
    stockCount: 18,
    colorOptions: [
      { name: 'Midnight Black', hex: '#1C1810', code: 'MB' },
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
    ],
    sizeOptions: [
      { size: 'One Size', label: 'One Size', inStock: true },
    ],
    relatedProducts: ['9', '11', '12', '1'],
  },
  {
    id: '11',
    slug: 'card-holder-wallet',
    name: 'Card Holder Wallet',
    category: 'Men · Wallets',
    gender: 'men',
    type: 'wallet',
    price: 55,
    originalPrice: 70,
    origin: 'Nappa leather · Sialkot',
    leather: 'Nappa',
    imageUrl: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👛',
    badge: 'Sale',
    rating: 4.6,
    reviewCount: 54,
    averageRating: 4.6,
    sections: ['featured'],
    colors: ['#7C3A2D', '#1C1810'],
    inStock: true,
    stockCount: 30,
    colorOptions: [
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
      { name: 'Midnight Black', hex: '#1C1810', code: 'MB' },
    ],
    sizeOptions: [
      { size: 'One Size', label: 'One Size', inStock: true },
    ],
    relatedProducts: ['9', '10', '12', '1'],
  },
  // Men's Belts (2)
  {
    id: '12',
    slug: 'brass-buckle-belt',
    name: 'Brass Buckle Belt',
    category: 'Men · Belts',
    gender: 'men',
    type: 'belt',
    price: 78,
    origin: 'Full-grain leather · Sialkot',
    leather: 'Full-grain',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👔',
    rating: 4.9,
    reviewCount: 124,
    averageRating: 4.9,
    sections: ['featured', 'rated'],
    ratingNum: 4.9,
    colors: ['#1C1810', '#3A2010'],
    inStock: true,
    stockCount: 12,
    colorOptions: [
      { name: 'Midnight Black', hex: '#1C1810', code: 'MB' },
      { name: 'Dark Brown', hex: '#3A2010', code: 'DB' },
    ],
    sizeOptions: [
      { size: '30', label: '30', inStock: true },
      { size: '32', label: '32', inStock: true },
      { size: '34', label: '34', inStock: true },
      { size: '36', label: '36', inStock: true },
      { size: '38', label: '38', inStock: true },
      { size: '40', label: '40', inStock: true },
    ],
    relatedProducts: ['13', '9', '10', '11'],
  },
  {
    id: '13',
    slug: 'classic-leather-belt',
    name: 'Classic Leather Belt',
    category: 'Men · Belts',
    gender: 'men',
    type: 'belt',
    price: 68,
    origin: 'Vegetable-tanned · Sialkot',
    leather: 'Vegetable-tanned',
    imageUrl: 'https://images.unsplash.com/photo-1624526267942-ab67cb38d042?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👔',
    badge: 'Hot',
    rating: 4.7,
    reviewCount: 98,
    averageRating: 4.7,
    sections: ['featured', 'selling'],
    rank: 4,
    colors: ['#1C1810', '#3A2010'],
    inStock: true,
    stockCount: 16,
    colorOptions: [
      { name: 'Midnight Black', hex: '#1C1810', code: 'MB' },
      { name: 'Dark Brown', hex: '#3A2010', code: 'DB' },
    ],
    sizeOptions: [
      { size: '30', label: '30', inStock: true },
      { size: '32', label: '32', inStock: true },
      { size: '34', label: '34', inStock: true },
      { size: '36', label: '36', inStock: true },
      { size: '38', label: '38', inStock: true },
      { size: '40', label: '40', inStock: true },
    ],
    relatedProducts: ['12', '9', '10', '11'],
  },
  // Women's Jackets (4)
  {
    id: '14',
    slug: 'zara-moto-jacket',
    name: 'Zara Moto Jacket',
    category: 'Women · Jackets',
    gender: 'women',
    type: 'jacket',
    price: 245,
    originalPrice: 320,
    origin: 'Nappa leather · Sialkot',
    leather: 'Nappa',
    imageUrl: 'https://images.unsplash.com/photo-1595777712802-4f3f84b5e9d9?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '🧥',
    badge: 'Sale',
    rating: 4.8,
    reviewCount: 73,
    averageRating: 4.8,
    sections: ['featured', 'new'],
    colors: ['#7C3A2D', '#5A2820', '#C9A96E'],
    inStock: true,
    stockCount: 9,
    colorOptions: [
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
      { name: 'Wine Red', hex: '#5A2820', code: 'WR' },
      { name: 'Brass Gold', hex: '#C9A96E', code: 'BG' },
    ],
    sizeOptions: [
      { size: 'XS', label: 'XS', inStock: true },
      { size: 'S', label: 'S', inStock: true },
      { size: 'M', label: 'M', inStock: true },
      { size: 'L', label: 'L', inStock: true },
      { size: 'XL', label: 'XL', inStock: true },
    ],
    relatedProducts: ['15', '16', '17', '22'],
  },
  {
    id: '15',
    slug: 'elegant-leather-jacket',
    name: 'Elegant Leather Jacket',
    category: 'Women · Jackets',
    gender: 'women',
    type: 'jacket',
    price: 275,
    origin: 'Soft lamb leather · Sialkot',
    leather: 'Lamb',
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '🧥',
    badge: 'New',
    rating: 4.9,
    reviewCount: 101,
    averageRating: 4.9,
    sections: ['featured', 'new', 'rated'],
    ratingNum: 4.9,
    colors: ['#8A7060', '#C9A96E'],
    inStock: true,
    stockCount: 4,
    colorOptions: [
      { name: 'Taupe', hex: '#8A7060', code: 'TA' },
      { name: 'Brass Gold', hex: '#C9A96E', code: 'BG' },
    ],
    sizeOptions: [
      { size: 'XS', label: 'XS', inStock: true },
      { size: 'S', label: 'S', inStock: true },
      { size: 'M', label: 'M', inStock: true },
      { size: 'L', label: 'L', inStock: false },
      { size: 'XL', label: 'XL', inStock: true },
    ],
    relatedProducts: ['14', '16', '17', '23'],
  },
  {
    id: '16',
    slug: 'casual-denim-jacket',
    name: 'Casual Denim Jacket',
    category: 'Women · Jackets',
    gender: 'women',
    type: 'jacket',
    price: 165,
    origin: 'Premium denim · Sialkot',
    leather: 'Denim',
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '🧥',
    rating: 4.7,
    reviewCount: 82,
    averageRating: 4.7,
    sections: ['featured'],
    colors: ['#1C1810', '#2A1810'],
    inStock: true,
    stockCount: 11,
    colorOptions: [
      { name: 'Midnight Black', hex: '#1C1810', code: 'MB' },
      { name: 'Charcoal', hex: '#2A1810', code: 'CH' },
    ],
    sizeOptions: [
      { size: 'XS', label: 'XS', inStock: true },
      { size: 'S', label: 'S', inStock: true },
      { size: 'M', label: 'M', inStock: true },
      { size: 'L', label: 'L', inStock: true },
      { size: 'XL', label: 'XL', inStock: true },
    ],
    relatedProducts: ['14', '15', '17', '22'],
  },
  {
    id: '17',
    slug: 'oversized-leather-jacket',
    name: 'Oversized Leather Jacket',
    category: 'Women · Jackets',
    gender: 'women',
    type: 'jacket',
    price: 295,
    origin: 'Full-grain leather · Sialkot',
    leather: 'Full-grain',
    imageUrl: 'https://images.unsplash.com/photo-1590736969955-71cc94901144?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '🧥',
    badge: 'Hot',
    rating: 4.9,
    reviewCount: 156,
    averageRating: 4.9,
    sections: ['featured', 'selling', 'rated'],
    rank: 5,
    ratingNum: 4.9,
    colors: ['#7C3A2D', '#C9A96E'],
    inStock: true,
    stockCount: 2,
    colorOptions: [
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
      { name: 'Brass Gold', hex: '#C9A96E', code: 'BG' },
    ],
    sizeOptions: [
      { size: 'XS', label: 'XS', inStock: true },
      { size: 'S', label: 'S', inStock: true },
      { size: 'M', label: 'M', inStock: false },
      { size: 'L', label: 'L', inStock: true },
      { size: 'XL', label: 'XL', inStock: true },
    ],
    relatedProducts: ['14', '15', '16', '23'],
  },
  // Women's Shoes (4)
  {
    id: '18',
    slug: 'sialkot-block-heel',
    name: 'Sialkot Block Heel',
    category: 'Women · Shoes',
    gender: 'women',
    type: 'shoe',
    price: 158,
    origin: 'Smooth leather · Sialkot',
    leather: 'Smooth',
    imageUrl: 'https://images.unsplash.com/photo-1543163521-9efcc06b9005?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👠',
    rating: 4.6,
    reviewCount: 38,
    averageRating: 4.6,
    sections: ['featured'],
    colors: ['#7C3A2D', '#1C1810'],
    inStock: true,
    stockCount: 7,
    colorOptions: [
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
      { name: 'Midnight Black', hex: '#1C1810', code: 'MB' },
    ],
    sizeOptions: [
      { size: '5', label: '5', inStock: true },
      { size: '5.5', label: '5.5', inStock: true },
      { size: '6', label: '6', inStock: true },
      { size: '6.5', label: '6.5', inStock: true },
      { size: '7', label: '7', inStock: true },
      { size: '7.5', label: '7.5', inStock: true },
      { size: '8', label: '8', inStock: true },
      { size: '8.5', label: '8.5', inStock: true },
      { size: '9', label: '9', inStock: true },
      { size: '10', label: '10', inStock: true },
    ],
    relatedProducts: ['19', '20', '21', '25'],
  },
  {
    id: '19',
    slug: 'elegant-leather-pump',
    name: 'Elegant Leather Pump',
    category: 'Women · Shoes',
    gender: 'women',
    type: 'shoe',
    price: 189,
    origin: 'Patent leather · Sialkot',
    leather: 'Patent',
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👠',
    badge: 'New',
    rating: 4.8,
    reviewCount: 64,
    averageRating: 4.8,
    sections: ['featured', 'new'],
    colors: ['#1C1810', '#7C3A2D'],
    inStock: true,
    stockCount: 10,
    colorOptions: [
      { name: 'Midnight Black', hex: '#1C1810', code: 'MB' },
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
    ],
    sizeOptions: [
      { size: '5', label: '5', inStock: true },
      { size: '6', label: '6', inStock: true },
      { size: '7', label: '7', inStock: true },
      { size: '8', label: '8', inStock: true },
      { size: '9', label: '9', inStock: true },
      { size: '10', label: '10', inStock: true },
    ],
    relatedProducts: ['18', '20', '21', '26'],
  },
  {
    id: '20',
    slug: 'classic-leather-loafer-women',
    name: 'Classic Leather Loafer',
    category: 'Women · Shoes',
    gender: 'women',
    type: 'shoe',
    price: 175,
    originalPrice: 220,
    origin: 'Premium leather · Sialkot',
    leather: 'Premium',
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👠',
    badge: 'Sale',
    rating: 4.7,
    reviewCount: 51,
    averageRating: 4.7,
    sections: ['featured'],
    colors: ['#7C3A2D', '#C9A96E', '#1C1810'],
    inStock: true,
    stockCount: 14,
    colorOptions: [
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
      { name: 'Brass Gold', hex: '#C9A96E', code: 'BG' },
      { name: 'Midnight Black', hex: '#1C1810', code: 'MB' },
    ],
    sizeOptions: [
      { size: '5', label: '5', inStock: true },
      { size: '6', label: '6', inStock: true },
      { size: '7', label: '7', inStock: true },
      { size: '8', label: '8', inStock: true },
      { size: '9', label: '9', inStock: true },
      { size: '10', label: '10', inStock: true },
    ],
    relatedProducts: ['18', '19', '21', '25'],
  },
  {
    id: '21',
    slug: 'comfortable-flat-shoe',
    name: 'Comfortable Flat Shoe',
    category: 'Women · Shoes',
    gender: 'women',
    type: 'shoe',
    price: 145,
    origin: 'Soft leather · Sialkot',
    leather: 'Soft',
    imageUrl: 'https://images.unsplash.com/photo-1543163521-9efcc06b9005?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👠',
    badge: 'Hot',
    rating: 4.9,
    reviewCount: 119,
    averageRating: 4.9,
    sections: ['featured', 'selling'],
    rank: 3,
    colors: ['#7C3A2D', '#C9A96E', '#1C1810'],
    inStock: true,
    stockCount: 22,
    colorOptions: [
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
      { name: 'Brass Gold', hex: '#C9A96E', code: 'BG' },
      { name: 'Midnight Black', hex: '#1C1810', code: 'MB' },
    ],
    sizeOptions: [
      { size: '5', label: '5', inStock: true },
      { size: '6', label: '6', inStock: true },
      { size: '7', label: '7', inStock: true },
      { size: '8', label: '8', inStock: true },
      { size: '9', label: '9', inStock: true },
      { size: '10', label: '10', inStock: true },
    ],
    relatedProducts: ['18', '19', '20', '26'],
  },
  // Women's Wallets (3)
  {
    id: '22',
    slug: 'zip-around-purse',
    name: 'Zip Around Purse',
    category: 'Women · Wallets',
    gender: 'women',
    type: 'wallet',
    price: 89,
    origin: 'Grain leather · Sialkot',
    leather: 'Grain',
    imageUrl: 'https://images.unsplash.com/photo-1467049351846-69133ffd07d1?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '💼',
    badge: 'New',
    rating: 4.8,
    reviewCount: 52,
    averageRating: 4.8,
    sections: ['featured', 'new'],
    colors: ['#7C3A2D', '#C9A96E'],
    inStock: true,
    stockCount: 13,
    colorOptions: [
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
      { name: 'Brass Gold', hex: '#C9A96E', code: 'BG' },
    ],
    sizeOptions: [
      { size: 'One Size', label: 'One Size', inStock: true },
    ],
    relatedProducts: ['23', '24', '25', '14'],
  },
  {
    id: '23',
    slug: 'premium-leather-clutch',
    name: 'Premium Leather Clutch',
    category: 'Women · Wallets',
    gender: 'women',
    type: 'wallet',
    price: 105,
    origin: 'Full-grain leather · Sialkot',
    leather: 'Full-grain',
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '💼',
    rating: 4.9,
    reviewCount: 78,
    averageRating: 4.9,
    sections: ['featured', 'rated'],
    ratingNum: 4.8,
    colors: ['#7C3A2D', '#C9A96E'],
    inStock: true,
    stockCount: 8,
    colorOptions: [
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
      { name: 'Brass Gold', hex: '#C9A96E', code: 'BG' },
    ],
    sizeOptions: [
      { size: 'One Size', label: 'One Size', inStock: true },
    ],
    relatedProducts: ['22', '24', '26', '15'],
  },
  {
    id: '24',
    slug: 'compact-card-wallet',
    name: 'Compact Card Wallet',
    category: 'Women · Wallets',
    gender: 'women',
    type: 'wallet',
    price: 72,
    originalPrice: 95,
    origin: 'Nappa leather · Sialkot',
    leather: 'Nappa',
    imageUrl: 'https://images.unsplash.com/photo-1627123834957-fc67c41db6dc?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '💼',
    badge: 'Sale',
    rating: 4.6,
    reviewCount: 43,
    averageRating: 4.6,
    sections: ['featured'],
    colors: ['#7C3A2D', '#C9A96E'],
    inStock: true,
    stockCount: 19,
    colorOptions: [
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
      { name: 'Brass Gold', hex: '#C9A96E', code: 'BG' },
    ],
    sizeOptions: [
      { size: 'One Size', label: 'One Size', inStock: true },
    ],
    relatedProducts: ['22', '23', '25', '14'],
  },
  // Women's Bags (4)
  {
    id: '25',
    slug: 'sialkot-tote-bag',
    name: 'Sialkot Tote Bag',
    category: 'Women · Bags',
    gender: 'women',
    type: 'bag',
    price: 185,
    origin: 'Pebbled leather · Sialkot',
    leather: 'Pebbled',
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👜',
    badge: 'New',
    rating: 4.9,
    reviewCount: 42,
    averageRating: 4.9,
    sections: ['featured', 'new'],
    colors: ['#7C3A2D', '#C9A96E'],
    inStock: true,
    stockCount: 6,
    colorOptions: [
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
      { name: 'Brass Gold', hex: '#C9A96E', code: 'BG' },
    ],
    sizeOptions: [
      { size: 'One Size', label: 'One Size', inStock: true },
    ],
    relatedProducts: ['26', '27', '28', '22'],
  },
  {
    id: '26',
    slug: 'crossbody-leather-bag',
    name: 'Crossbody Leather Bag',
    category: 'Women · Bags',
    gender: 'women',
    type: 'bag',
    price: 195,
    origin: 'Full-grain leather · Sialkot',
    leather: 'Full-grain',
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👜',
    badge: 'Hot',
    rating: 4.9,
    reviewCount: 134,
    averageRating: 4.9,
    sections: ['featured', 'selling'],
    rank: 1,
    colors: ['#7C3A2D', '#5A2820', '#C9A96E'],
    inStock: true,
    stockCount: 3,
    colorOptions: [
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
      { name: 'Wine Red', hex: '#5A2820', code: 'WR' },
      { name: 'Brass Gold', hex: '#C9A96E', code: 'BG' },
    ],
    sizeOptions: [
      { size: 'One Size', label: 'One Size', inStock: true },
    ],
    relatedProducts: ['25', '27', '28', '23'],
  },
  {
    id: '27',
    slug: 'elegant-shoulder-bag',
    name: 'Elegant Shoulder Bag',
    category: 'Women · Bags',
    gender: 'women',
    type: 'bag',
    price: 215,
    originalPrice: 280,
    origin: 'Nappa leather · Sialkot',
    leather: 'Nappa',
    imageUrl: 'https://images.unsplash.com/photo-1566150905458-1bf049d3decb?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👜',
    badge: 'Sale',
    rating: 4.7,
    reviewCount: 89,
    averageRating: 4.7,
    sections: ['featured'],
    colors: ['#C9A96E', '#7C3A2D'],
    inStock: true,
    stockCount: 11,
    colorOptions: [
      { name: 'Brass Gold', hex: '#C9A96E', code: 'BG' },
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
    ],
    sizeOptions: [
      { size: 'One Size', label: 'One Size', inStock: true },
    ],
    relatedProducts: ['25', '26', '28', '22'],
  },
  {
    id: '28',
    slug: 'structured-leather-handbag',
    name: 'Structured Leather Handbag',
    category: 'Women · Bags',
    gender: 'women',
    type: 'bag',
    price: 245,
    origin: 'Premium leather · Sialkot',
    leather: 'Premium',
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👜',
    rating: 4.8,
    reviewCount: 76,
    averageRating: 4.8,
    sections: ['featured', 'rated'],
    ratingNum: 4.8,
    colors: ['#7C3A2D', '#C9A96E'],
    inStock: true,
    stockCount: 5,
    colorOptions: [
      { name: 'Cognac Brown', hex: '#7C3A2D', code: 'CB' },
      { name: 'Brass Gold', hex: '#C9A96E', code: 'BG' },
    ],
    sizeOptions: [
      { size: 'One Size', label: 'One Size', inStock: true },
    ],
    relatedProducts: ['25', '26', '27', '23'],
  },
];

// Helper functions for fetching products by section
export function getProductsBySection(sectionId: SectionType): Product[] {
  return products.filter(
    (p) => p.sections && p.sections.includes(sectionId)
  );
}

export function getNewArrivals(): Product[] {
  return products
    .filter((p) => p.badge === 'New')
    .sort((a, b) => b.reviewCount - a.reviewCount)
    .slice(0, 12);
}

export function getTopSelling(): Product[] {
  return products
    .filter((p) => p.rank !== undefined)
    .sort((a, b) => (a.rank || 0) - (b.rank || 0))
    .slice(0, 8);
}

export function getTopRated(): Product[] {
  return products
    .filter((p) => p.ratingNum !== undefined && p.ratingNum >= 4.8)
    .sort((a, b) => (b.ratingNum || 0) - (a.ratingNum || 0))
    .slice(0, 12);
}

export function getExclusive(): Product[] {
  return products
    .filter((p) => p.isLimited === true)
    .slice(0, 12);
}

// Helper function to get a single product by slug
export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug || p.id === slug);
}

// Helper function to get a single product by ID
export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

// Helper function to get related products
export function getRelatedProducts(productId: string, limit = 4): Product[] {
  const product = getProductById(productId);
  if (!product || !product.relatedProducts) return [];
  
  return product.relatedProducts
    .map((id) => getProductById(id))
    .filter((p) => p !== undefined) as Product[];
}
