import { Product } from '@/types/product';

export const products: Product[] = [
  {
    id: '1',
    name: 'Heritage Biker Jacket',
    category: 'Men · Jackets',
    gender: 'men',
    type: 'jacket',
    price: 289,
    originalPrice: 380,
    origin: 'Full-grain cowhide · Sialkot',
    leather: 'Full-grain',
    emoji: '🧥',
    badge: 'Bestseller',
    rating: 4.9,
    reviews: 128,
  },
  {
    id: '2',
    name: 'Slim Bifold Wallet',
    category: 'Men · Wallets',
    gender: 'men',
    type: 'wallet',
    price: 65,
    origin: 'Vegetable-tanned · Sialkot',
    leather: 'Vegetable-tanned',
    emoji: '👛',
    rating: 4.8,
    reviews: 85,
  },
  {
    id: '3',
    name: 'Sialkot Tote Bag',
    category: 'Women · Bags',
    gender: 'women',
    type: 'bag',
    price: 185,
    origin: 'Pebbled leather · Sialkot',
    leather: 'Pebbled',
    emoji: '👜',
    badge: 'New',
    rating: 4.9,
    reviews: 42,
  },
  {
    id: '4',
    name: 'Oxford Derby Shoe',
    category: 'Men · Shoes',
    gender: 'men',
    type: 'shoe',
    price: 195,
    origin: 'Calfskin leather · Sialkot',
    leather: 'Calfskin',
    emoji: '👞',
    rating: 4.7,
    reviews: 56,
  },
  {
    id: '5',
    name: 'Zara Moto Jacket',
    category: 'Women · Jackets',
    gender: 'women',
    type: 'jacket',
    price: 245,
    originalPrice: 320,
    origin: 'Nappa leather · Sialkot',
    leather: 'Nappa',
    emoji: '🧥',
    badge: 'Sale',
    rating: 4.8,
    reviews: 73,
  },
  {
    id: '6',
    name: 'Brass Buckle Belt',
    category: 'Men · Belts',
    gender: 'men',
    type: 'belt',
    price: 78,
    origin: 'Full-grain leather · Sialkot',
    leather: 'Full-grain',
    emoji: '👔',
    rating: 4.9,
    reviews: 124,
  },
  {
    id: '7',
    name: 'Sialkot Block Heel',
    category: 'Women · Shoes',
    gender: 'women',
    type: 'shoe',
    price: 158,
    origin: 'Smooth leather · Sialkot',
    leather: 'Smooth',
    emoji: '👠',
    rating: 4.6,
    reviews: 38,
  },
  {
    id: '8',
    name: 'Zip Around Purse',
    category: 'Women · Wallets',
    gender: 'women',
    type: 'wallet',
    price: 89,
    origin: 'Grain leather · Sialkot',
    leather: 'Grain',
    emoji: '💼',
    badge: 'New',
    rating: 4.8,
    reviews: 52,
  },
];
