import { Product } from '@/types/product';

export const products: Product[] = [
  // Men's Jackets (4)
  {
    id: '1',
    name: 'Heritage Biker Jacket',
    category: 'Men · Jackets',
    gender: 'men',
    type: 'jacket',
    price: 289,
    originalPrice: 380,
    origin: 'Full-grain cowhide · Sialkot',
    leather: 'Full-grain',
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '🧥',
    badge: 'Bestseller',
    rating: 4.9,
    reviews: 128,
  },
  {
    id: '2',
    name: 'Classic Leather Blazer',
    category: 'Men · Jackets',
    gender: 'men',
    type: 'jacket',
    price: 325,
    origin: 'Premium calf leather · Sialkot',
    leather: 'Calf',
    imageUrl: 'https://images.unsplash.com/photo-1539533057440-7cf90262271e?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '🧥',
    badge: 'New',
    rating: 4.8,
    reviews: 94,
  },
  {
    id: '3',
    name: 'Aviator Leather Jacket',
    category: 'Men · Jackets',
    gender: 'men',
    type: 'jacket',
    price: 299,
    origin: 'Vegetable-tanned · Sialkot',
    leather: 'Vegetable-tanned',
    imageUrl: 'https://images.unsplash.com/photo-1590736969955-71cc94901144?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '🧥',
    rating: 4.7,
    reviews: 112,
  },
  {
    id: '4',
    name: 'Minimal Leather Jacket',
    category: 'Men · Jackets',
    gender: 'men',
    type: 'jacket',
    price: 275,
    originalPrice: 350,
    origin: 'Nappa leather · Sialkot',
    leather: 'Nappa',
    imageUrl: 'https://images.unsplash.com/photo-1597982212624-e27f42e73144?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '🧥',
    badge: 'Sale',
    rating: 4.6,
    reviews: 87,
  },
  // Men's Shoes (4)
  {
    id: '5',
    name: 'Oxford Derby Shoe',
    category: 'Men · Shoes',
    gender: 'men',
    type: 'shoe',
    price: 195,
    origin: 'Calfskin leather · Sialkot',
    leather: 'Calfskin',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👞',
    rating: 4.7,
    reviews: 56,
  },
  {
    id: '6',
    name: 'Italian Loafer',
    category: 'Men · Shoes',
    gender: 'men',
    type: 'shoe',
    price: 185,
    origin: 'Premium leather · Sialkot',
    leather: 'Premium',
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👞',
    badge: 'Bestseller',
    rating: 4.8,
    reviews: 142,
  },
  {
    id: '7',
    name: 'Chelsea Boot',
    category: 'Men · Shoes',
    gender: 'men',
    type: 'shoe',
    price: 225,
    origin: 'Full-grain leather · Sialkot',
    leather: 'Full-grain',
    imageUrl: 'https://images.unsplash.com/photo-1543163521-9efcc06b9005?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👞',
    rating: 4.9,
    reviews: 128,
  },
  {
    id: '8',
    name: 'Casual Leather Sneaker',
    category: 'Men · Shoes',
    gender: 'men',
    type: 'shoe',
    price: 165,
    originalPrice: 210,
    origin: 'Soft leather · Sialkot',
    leather: 'Soft',
    imageUrl: 'https://images.unsplash.com/photo-1549928736-42cabea2b519?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👞',
    badge: 'Sale',
    rating: 4.5,
    reviews: 73,
  },
  // Men's Wallets (3)
  {
    id: '9',
    name: 'Slim Bifold Wallet',
    category: 'Men · Wallets',
    gender: 'men',
    type: 'wallet',
    price: 65,
    origin: 'Vegetable-tanned · Sialkot',
    leather: 'Vegetable-tanned',
    imageUrl: 'https://images.unsplash.com/photo-1627123834957-fc67c41db6dc?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👛',
    rating: 4.8,
    reviews: 85,
  },
  {
    id: '10',
    name: 'Premium Trifold Wallet',
    category: 'Men · Wallets',
    gender: 'men',
    type: 'wallet',
    price: 85,
    origin: 'Full-grain leather · Sialkot',
    leather: 'Full-grain',
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👛',
    badge: 'New',
    rating: 4.9,
    reviews: 67,
  },
  {
    id: '11',
    name: 'Card Holder Wallet',
    category: 'Men · Wallets',
    gender: 'men',
    type: 'wallet',
    price: 55,
    originalPrice: 70,
    origin: 'Nappa leather · Sialkot',
    leather: 'Nappa',
    imageUrl: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👛',
    badge: 'Sale',
    rating: 4.6,
    reviews: 54,
  },
  // Men's Belts (2)
  {
    id: '12',
    name: 'Brass Buckle Belt',
    category: 'Men · Belts',
    gender: 'men',
    type: 'belt',
    price: 78,
    origin: 'Full-grain leather · Sialkot',
    leather: 'Full-grain',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👔',
    rating: 4.9,
    reviews: 124,
  },
  {
    id: '13',
    name: 'Classic Leather Belt',
    category: 'Men · Belts',
    gender: 'men',
    type: 'belt',
    price: 68,
    origin: 'Vegetable-tanned · Sialkot',
    leather: 'Vegetable-tanned',
    imageUrl: 'https://images.unsplash.com/photo-1624526267942-ab67cb38d042?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👔',
    badge: 'Bestseller',
    rating: 4.7,
    reviews: 98,
  },
  // Women's Jackets (4)
  {
    id: '14',
    name: 'Zara Moto Jacket',
    category: 'Women · Jackets',
    gender: 'women',
    type: 'jacket',
    price: 245,
    originalPrice: 320,
    origin: 'Nappa leather · Sialkot',
    leather: 'Nappa',
    imageUrl: 'https://images.unsplash.com/photo-1595777712802-4f3f84b5e9d9?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '🧥',
    badge: 'Sale',
    rating: 4.8,
    reviews: 73,
  },
  {
    id: '15',
    name: 'Elegant Leather Jacket',
    category: 'Women · Jackets',
    gender: 'women',
    type: 'jacket',
    price: 275,
    origin: 'Soft lamb leather · Sialkot',
    leather: 'Lamb',
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '🧥',
    badge: 'New',
    rating: 4.9,
    reviews: 101,
  },
  {
    id: '16',
    name: 'Casual Denim Jacket',
    category: 'Women · Jackets',
    gender: 'women',
    type: 'jacket',
    price: 165,
    origin: 'Premium denim · Sialkot',
    leather: 'Denim',
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '🧥',
    rating: 4.7,
    reviews: 82,
  },
  {
    id: '17',
    name: 'Oversized Leather Jacket',
    category: 'Women · Jackets',
    gender: 'women',
    type: 'jacket',
    price: 295,
    origin: 'Full-grain leather · Sialkot',
    leather: 'Full-grain',
    imageUrl: 'https://images.unsplash.com/photo-1590736969955-71cc94901144?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '🧥',
    badge: 'Bestseller',
    rating: 4.9,
    reviews: 156,
  },
  // Women's Shoes (4)
  {
    id: '18',
    name: 'Sialkot Block Heel',
    category: 'Women · Shoes',
    gender: 'women',
    type: 'shoe',
    price: 158,
    origin: 'Smooth leather · Sialkot',
    leather: 'Smooth',
    imageUrl: 'https://images.unsplash.com/photo-1543163521-9efcc06b9005?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👠',
    rating: 4.6,
    reviews: 38,
  },
  {
    id: '19',
    name: 'Elegant Leather Pump',
    category: 'Women · Shoes',
    gender: 'women',
    type: 'shoe',
    price: 189,
    origin: 'Patent leather · Sialkot',
    leather: 'Patent',
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👠',
    badge: 'New',
    rating: 4.8,
    reviews: 64,
  },
  {
    id: '20',
    name: 'Classic Leather Loafer',
    category: 'Women · Shoes',
    gender: 'women',
    type: 'shoe',
    price: 175,
    originalPrice: 220,
    origin: 'Premium leather · Sialkot',
    leather: 'Premium',
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👠',
    badge: 'Sale',
    rating: 4.7,
    reviews: 51,
  },
  {
    id: '21',
    name: 'Comfortable Flat Shoe',
    category: 'Women · Shoes',
    gender: 'women',
    type: 'shoe',
    price: 145,
    origin: 'Soft leather · Sialkot',
    leather: 'Soft',
    imageUrl: 'https://images.unsplash.com/photo-1543163521-9efcc06b9005?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👠',
    badge: 'Bestseller',
    rating: 4.9,
    reviews: 119,
  },
  // Women's Wallets (3)
  {
    id: '22',
    name: 'Zip Around Purse',
    category: 'Women · Wallets',
    gender: 'women',
    type: 'wallet',
    price: 89,
    origin: 'Grain leather · Sialkot',
    leather: 'Grain',
    imageUrl: 'https://images.unsplash.com/photo-1467049351846-69133ffd07d1?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '💼',
    badge: 'New',
    rating: 4.8,
    reviews: 52,
  },
  {
    id: '23',
    name: 'Premium Leather Clutch',
    category: 'Women · Wallets',
    gender: 'women',
    type: 'wallet',
    price: 105,
    origin: 'Full-grain leather · Sialkot',
    leather: 'Full-grain',
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '💼',
    rating: 4.9,
    reviews: 78,
  },
  {
    id: '24',
    name: 'Compact Card Wallet',
    category: 'Women · Wallets',
    gender: 'women',
    type: 'wallet',
    price: 72,
    originalPrice: 95,
    origin: 'Nappa leather · Sialkot',
    leather: 'Nappa',
    imageUrl: 'https://images.unsplash.com/photo-1627123834957-fc67c41db6dc?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '💼',
    badge: 'Sale',
    rating: 4.6,
    reviews: 43,
  },
  // Women's Bags (4)
  {
    id: '25',
    name: 'Sialkot Tote Bag',
    category: 'Women · Bags',
    gender: 'women',
    type: 'bag',
    price: 185,
    origin: 'Pebbled leather · Sialkot',
    leather: 'Pebbled',
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👜',
    badge: 'New',
    rating: 4.9,
    reviews: 42,
  },
  {
    id: '26',
    name: 'Crossbody Leather Bag',
    category: 'Women · Bags',
    gender: 'women',
    type: 'bag',
    price: 195,
    origin: 'Full-grain leather · Sialkot',
    leather: 'Full-grain',
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👜',
    badge: 'Bestseller',
    rating: 4.9,
    reviews: 134,
  },
  {
    id: '27',
    name: 'Elegant Shoulder Bag',
    category: 'Women · Bags',
    gender: 'women',
    type: 'bag',
    price: 215,
    originalPrice: 280,
    origin: 'Nappa leather · Sialkot',
    leather: 'Nappa',
    imageUrl: 'https://images.unsplash.com/photo-1566150905458-1bf049d3decb?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👜',
    badge: 'Sale',
    rating: 4.7,
    reviews: 89,
  },
  {
    id: '28',
    name: 'Structured Leather Handbag',
    category: 'Women · Bags',
    gender: 'women',
    type: 'bag',
    price: 245,
    origin: 'Premium leather · Sialkot',
    leather: 'Premium',
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=750&fit=crop&crop=entropy&q=80',
    emoji: '👜',
    rating: 4.8,
    reviews: 76,
  },
];
